baseURL = "https://Lady-Lex.github.io/"
languageCode = "zh-cn"
title = "Lex's Test Site"
theme = "PaperMod"


[build]
  publishDir = "public"
  buildFuture = true


[params]
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  mainSections = ["posts"]