baseURL = "https://Lady-Lex.github.io/"
languageCode = "zh-cn"
title = "Lex's Test Site"
theme = "PaperMod"


[build]
  publishDir = "public"

# 内容配置
[params]
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  # 指定在首页显示的内容类型
  mainSections = ["posts"]