baseURL = "https://Lady-Lex.github.io/"
languageCode = "en-us"
title = "Lex's Lite Page"
theme = "PaperMod"


[build]
  publishDir = "public"
  buildFuture = true


[params]
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  mainSections = ["posts"]