baseURL = "https://Lady-Lex.github.io/"
languageCode = "en-us"
title = "Lex's Lite Page"
theme = "PaperMod"


[build]
  publishDir = "public"
  buildFuture = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]


[params]
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  mainSections = ["posts"]
  ShowToc = true                 # 显示目录
  TocOpen = true                 # 默认展开目录（便于快速导航）
  math = true                    # 启用数学支持
  